window.FACES_DATA = [
  {
    name: "Данила Гульков",
    gender: "мужской",
    age: 25,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1010929.jpg",
    education: "ГИТИС",
    hairColor: "Русый",
    hairLength: "Средняя длина",
    eyeColor: "Серо-голубой",
    height: 180,
    bodyType: "Стройное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1010929.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1049761.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1049760.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1010930.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1010931.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u50220/video/2628467/2628467_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3309938/"
  },
  {
    name: "Богдан Карчевский",
    gender: "мужской",
    age: 19,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1076748.jpg",
    education: "ВТУ им. М.С. Щепкина",
    hairColor: "Русый",
    hairLength: "Короткие",
    eyeColor: "Серо-голубой",
    height: 180,
    bodyType: "Атлетичное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1076748.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1076757.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1076763.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1076758.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1076755.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u87833/video/2764033/2764033_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/4108095/"
  },
  {
    name: "Павел Федоров",
    gender: "мужской",
    age: 37,
    city: "Санкт-Петербург",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1082614.jpg",
    education: "СПбГИК",
    hairColor: "Русый",
    hairLength: "Короткие",
    eyeColor: "Серо-зеленый",
    height: 178,
    bodyType: "Атлетичное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1082614.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1082619.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1082618.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1082617.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1082616.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1082615.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u19691/video/2793061/2793061_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3163630/"
  },
  {
    name: "Александра Шеина",
    gender: "женский",
    age: 27,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1029495.jpg",
    education: "ФШР",
    hairColor: "Шатен",
    hairLength: "Каре",
    eyeColor: "Серо-голубой",
    height: 166,
    bodyType: "Среднее",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1029495.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1032980.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1029500.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1029499.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1029498.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1029497.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1029496.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1029491.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u40154/video/2528879/2528879_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/4057285/"
  },
  {
    name: "Юрий Могила",
    gender: "мужской",
    age: 40,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/989398.jpg",
    education: "ГИТИС",
    hairColor: "Русый",
    hairLength: "Короткие",
    eyeColor: "Серо-зеленый",
    height: 170,
    bodyType: "Атлетичное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/989398.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129274.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129271.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129270.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129267.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129258.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129256.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129255.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/988885.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u37793/video/3053342/3053342_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3132479/"
  },
  {
    name: "Олег Щербаченко",
    gender: "мужской",
    age: 20,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1055216.jpg",
    education: "ВГИК",
    hairColor: "Шатен",
    hairLength: "Средние",
    eyeColor: "Черный",
    height: 191,
    bodyType: "Атлетичное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1055216.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1055219.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1055217.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1055215.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1055212.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1055211.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u66822/video/3167750/3167750_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3848212/"
  },
];